#pragma config(Sensor, dgtl1,  pnue,           sensorDigitalOut)
#pragma config(Motor,  port1,           BR,            tmotorVex393HighSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           FL,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           liftR,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           L,             tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,            ,             tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           liftL,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           R,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           FR,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          BL,            tmotorVex393HighSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

const short leftButton = 1;
const short centerButton = 2;
const short rightButton = 4;
int autonomousChoice;

void waitForPress()
{
	while(nLCDButtons == 0){}
	wait1Msec(5);
}

void waitForRelease()
{
	while(nLCDButtons != 0){}
	wait1Msec(5);
}

void clearEnconders()
{
}

void haultYo()
{
	motor[port1] = 0;
	motor[port2] = 0;
	motor[port3] = 0;
	motor[port4] = 0;
	motor[port5] = 0;
	motor[port6] = 0;
	motor[port7] = 0;
	motor[port8] = 0;
	motor[port9] = 0;
	motor[port10] = 0;
}

void driveFoeward(int power, int dist)//With PID
{
//	clearEncoders();
	if(dist<150)
		{
		  while (abs(SensorValue[I2C_1]) < dist && abs(SensorValue[I2C_2]) < dist)
	  	{
			motor[port2] = power;
			motor[port10] = power;
			motor[port1] = power;
			motor[port9] = power;
			}
			haultYo();
		}

	else
		{

			while (abs(SensorValue[I2C_1]) < dist-100 && abs(SensorValue[I2C_2]) < dist-100)
				{
					motor[port2] = power;
					motor[port10] = power;
					motor[port1] = power;
					motor[port9] = power;
				}
	haultYo();
		while(abs(SensorValue[I2C_1]) < dist-50 && abs(SensorValue[I2C_1]) < dist-50)
		{
			motor[port2] = power/2;
			motor[port10] = power/2;
			motor[port1] = power/2;
			motor[port9] = power/2;
		}
		while(abs(SensorValue[I2C_1]) < dist && abs(SensorValue[I2C_1]) < dist)
		{
			motor[port2] = power/4;
			motor[port10] = power/4;
			motor[port1] = power/4;
			motor[port9] = power/4;
		}
		haultYo();
	}
}

void driveBackward(int power, int dist)//With PID
{
//	clearEncoders();
	if(dist<150)
	{
	  while (abs(SensorValue[I2C_1]) < dist && abs(SensorValue[I2C_2]) < dist)
	  {
			motor[port2] = -power;
			motor[port10] = -power;
			motor[port1] = -power;
			motor[port9] = -power;
		}
		haultYo();
		}

	else
	{

		while (abs(SensorValue[I2C_1]) < dist-100 && abs(SensorValue[I2C_2]) < dist-100)
		{
			motor[port2] = -power;
			motor[port10] = -power;
			motor[port1] = -power;
			motor[port9] = -power;
		}
	haultYo();
		while(abs(SensorValue[I2C_1]) < dist-50 && abs(SensorValue[I2C_1]) < dist-50)
		{
			motor[port2] = -power/2;
			motor[port10] = -power/2;
			motor[port1] = -power/2;
			motor[port9] = -power/2;
		}
		while(abs(SensorValue[I2C_1]) < dist && abs(SensorValue[I2C_1]) < dist)
		{
			motor[port2] = -power/4;
			motor[port10] = -power/4;
			motor[port1] = -power/4;
			motor[port9] = -power/4;
		}
		haultYo();
	}
}

void GyroPointTurnLeft(int degrees)//With PID
{
	SensorValue[in8] = 0;
	int degrees10 = degrees;
  int error = 5;

  //While the absolute value of the gyro is less than the desired rotation...
  while(abs(SensorValue[in8]) < degrees10 - 200)
  {
    //...continue turning
  	motor[port2] = -50;
  	motor[port10] = -50;
    motor[port1] = 50;
    motor[port9] = 50;
  }

  //Brief brake to stop some drift
  motor[port2] = 5;
  motor[port10] = 5;
  motor[port1] = -5;
  motor[port9] = -5;
  wait1Msec(250);

  //Second while loop to move the robot more slowly to its goal, also setting up a range
  //for the amount of acceptable error in the system
  while(abs(SensorValue[in8]) > degrees10 + error || abs(SensorValue[in8]) < degrees10 - error)
  {
    if(abs(SensorValue[in8]) > degrees10)
    {
    	motor[port2] = 35;
    	motor[port10] = 35;
      motor[port1] = -35;
      motor[port9] = -35;
    }
    else
    {
    	motor[port2] = -35;
    	motor[port10] = -35;
      motor[port1] = 35;
      motor[port9] = 35;
    }
  }
    //Stop
	haultYo();
}

void blueSkyrise()
{

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

  bLCDBacklight = true;

  SensorType[in8] = sensorNone;
  wait1Msec(1000);

  SensorType[in8] = sensorGyro;
  wait1Msec(1000);

  int count = 0;

  //------------- Beginning of User Interface Code ---------------
	//Clear LCD
	clearLCDLine(0);
	clearLCDLine(1);
	//Loop while center button is not pressed
	while(nLCDButtons != centerButton)
	{
		//Switch case that allows the user to choose from 4 different options
		switch(count){
		case 0: //Display 1st choice
			displayLCDCenteredString(0, "BLUE Non-Skyrise");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count = 3;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;
		case 1:	//Display 2nd choice
			displayLCDCenteredString(0, "BLUE Skyrise");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;
		case 2: //Display 3rd choice
			displayLCDCenteredString(0, "RED Non-Skyrise");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;
		case 3:
			//Display 4th choice
			displayLCDCenteredString(0, "RED Skyrise");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;
		case 4:
			//Display 5th choice
			displayLCDCenteredString(0, "Skills");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count = 0;
			}
			break;
		default:
			count = 0;
			break;
		}
		// Set global autonomousChoice variable to count
		autonomousChoice = count;
	}
	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  // .....................................................................................
  // Insert user code here.
  // .....................................................................................

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		motor[port10] = vexRT[Ch2] + vexRT[Ch1];//drive
		motor[port2] = vexRT[Ch2] + vexRT[Ch1];
		motor[port1] = vexRT[Ch2] - vexRT[Ch1];
		motor[port9] = vexRT[Ch2] - vexRT[Ch1];

		motor[port7] = -vexRT[Ch3];//lift
		motor[port4] = -vexRT[Ch3]; // 3.21 Rushing - reduced to 80% power to straighten lift
		motor[port3] = -vexRT[Ch3];
		motor[port8] = -vexRT[Ch3];

		if(vexRT[Btn6U] == 1) //pnueueueueueueueueueueueueueueueueueueueueueueueueueueueueueueueueueueueueueueueueueueueueueueu
			SensorValue[dgtl1] = 1;
		if(vexRT[Btn6D] == 1)
			SensorValue[dgtl1] = 0;

		if(vexRT[Btn5U] == 1) //other pnueueueueueueueueueueueueueueueueueueueueueueueueueueueueueueueueueueueueueueueueueueueu
			SensorValue[dgtl3] = 1;
		if(vexRT[Btn5D] == 1)
			SensorValue[dgtl3] = 0;


		while(vexRT[Btn8R] == 1)
			motor[port6] = 127;
		motor[port6] = 0;
		while(vexRT[Btn8L] == 1)
			motor[port6] = -127;
		motor[port6] = 0;
		}
}
